<?php

namespace AppBundle\Repository;

/**
 * FinishedGameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FinishedGameRepository extends \Doctrine\ORM\EntityRepository
{
        // On récupère le nombre de partie jouée
        public function CountAllGamePlayed()
        {
            $result = $this->getEntityManager()
                ->createQuery('
                    SELECT count(fg.id) total
                    FROM AppBundle:FinishedGame fg
                ')
                ->getResult();

            // On retourne le résultat
            return $result;
        }

        // On récupère le nombre de partie jouée
        public function CountAllFactionGameVictory()
        {
            $result = $this->getEntityManager()
                ->createQuery('
                    SELECT f.name, count(fg.id) total
                    FROM AppBundle:FinishedGame fg
                    JOIN fg.faction f
                    GROUP BY f.name
                ')
                ->getResult();

            // On retourne le résultat
            return $result;
        }

        // On récupère le nombre de killed par faction
        public function CountAllKilledByFaction()
        {
            $result = $this->getEntityManager()
                ->createQuery('
                    SELECT f.name, sum(p.killed) total
                    FROM AppBundle:FinishedGame fg
                    JOIN fg.faction f
                    JOIN fg.players p
                    GROUP BY f.name
                ')
                ->getResult();

            // On retourne le résultat
            return $result;
        }

        // On récupère le nombre de revived par faction
        public function CountAllRevivedByFaction()
        {
            $result = $this->getEntityManager()
                ->createQuery('
                    SELECT f.name, sum(p.revive) total
                    FROM AppBundle:FinishedGame fg
                    JOIN fg.faction f
                    JOIN fg.players p
                    GROUP BY f.name
                ')
                ->getResult();

            // On retourne le résultat
            return $result;
        }
}
