<?php

namespace AppBundle\Repository;

/**
 * OngoingGameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OngoingGameRepository extends \Doctrine\ORM\EntityRepository
{
    // Retourne les n dernières parties créées
    public function getLastCreatedGame($count = 4)
    {
        $result = $this->getEntityManager()
            ->createQuery('
                    SELECT og
                    FROM AppBundle:OngoingGame og
                    ORDER BY og.createdAt DESC
            ')
            ->setMaxResults($count)
            ->getResult();

        return $result;
    }
}
