<?php

namespace AppBundle\Repository;

use AppBundle\Entity\User;

/**
 * PlayersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
*/
class PlayersRepository extends \Doctrine\ORM\EntityRepository
{
   // récupère les 10 dernières partie du joueur
  public function findLastTenGames(User $user)
  {

    $result = $this->getEntityManager()
    ->createQuery('
    SELECT p
    FROM AppBundle:Players p
    WHERE p.user = :user
    ORDER BY p.id DESC'
    )
    ->setParameter('user', $user->getId())
    ->setMaxResults(10)
    ->getResult();

    // On retourne le(s) résultat()
    return $result;
  }
}
