<?php

namespace AppBundle\Repository;

/**
 * PresetSentenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PresetSentenceRepository extends \Doctrine\ORM\EntityRepository
{
}
