# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt
    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory: ~
        projetz_provider:
            entity:
                class: AppBundle:User
                property: username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            form_login:
                login_path: login
                check_path: login
                csrf_token_generator: security.csrf.token_manager
            logout:
                path:   /logout
                target: /

            provider: projetz_provider

            logout_on_user_change: true

    role_hierarchy:
        ROLE_ADMIN: ROLE_MANAGER
        ROLE_MANAGER: ROLE_USER

    access_control:
        # le rôle ROLE_ADMIN est nécessaire pour accéder aux pages /admin*
        - { path: ^/admin, roles: ROLE_ADMIN }

        # liste des routes accessibles en tant que visiteur
        # page d'accueil, inscription + connexion et pages statiques faq + contact admin
        - { path: ^/$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/signup, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/faq, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/contact$, roles: IS_AUTHENTICATED_ANONYMOUSLY }

        # toutes les autres routes nécessites d'être au moins connecté
        - { path: ^/, roles: ROLE_USER }
